In [1]:
import pandas as vAR_DSLAB_pd

from sklearn.linear_model import LinearRegression

vAR_DSLAB_HOUSE_PRICE_INPUT_DATA = vAR_DSLAB_pd.read_csv("C:/Users/DeepSphere.AI/Lab_Exercise/Unit-3/DSLAB_HOUSE_PRICE_DATA.csv")

vAR_DSLAB_HOUSE_PRICE_INPUT_DATA.head()

vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA = vAR_DSLAB_HOUSE_PRICE_INPUT_DATA

vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA_FEATURES = vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]

vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA_LABEL = vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA[['MEDV']]

vAR_DSLAB_MODEL = LinearRegression()

vAR_DSLAB_MODEL_TRAINING = vAR_DSLAB_MODEL.fit(vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA_FEATURES,vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA_LABEL)

vAR_DSLAB_MODEL_TRAINING 

vAR_DSLAB_HOUSE_PRICE_TEST_DATA = vAR_DSLAB_HOUSE_PRICE_TRAINING_DATA.iloc[20:52]

vAR_DSLAB_HOUSE_PRICE_TEST_DATA.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
20,1.25179,0.0,8.14,0,0.538,5.570,98.1,3.7979,4,307,21.0,376.57,21.02,13.6
21,0.85204,0.0,8.14,0,0.538,5.965,89.2,4.0123,4,307,21.0,392.53,13.83,19.6
22,1.23247,0.0,8.14,0,0.538,6.142,91.7,3.9769,4,307,21.0,396.90,18.72,15.2
23,0.98843,0.0,8.14,0,0.538,5.813,100.0,4.0952,4,307,21.0,394.54,19.88,14.5
24,0.75026,0.0,8.14,0,0.538,5.924,94.1,4.3996,4,307,21.0,394.33,16.30,15.6